blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("tag/<slug:tag_slug>/", views.PostListView.as_view(), name="list_by_tag"),
    path("<slug:post>/", views.PostDetailView.as_view(), name="detail"),
    path("<int:post_id>/share/", views.share, name="share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
]

# <int:year>/<int:month>/<int:day>/

visign_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # add this
from django.conf.urls.static import static  # add this
from django.core.management.utils import get_random_secret_key

# print('................')
# print(get_random_secret_key())
# print('................')
# ...........................................................
# default: "Django Administration"
# admin.site.site_header = 'DKIBUI BLOG'
# default: "Site administration"
admin.site.index_title = 'WELCOME TO DKIBUI BLOGS'
# default: "Django site admin"
admin.site.site_title = 'dkibui blog'
# ...........................................................

urlpatterns = [
    path('', include("blog.urls")),
    path('', include("about.urls")),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from datetime import timedelta
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date="publish")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = RichTextField()
    tags = TaggableManager()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=12, choices=Status.choices, default=Status.DRAFT
    )

    # Default manager
    objects = models.Manager()
    # The custom manager
    published = PublishedManager()

    class Meta:
        # default_manager_name = objects
        ordering = ("-publish",)
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:detail",
            args=[self.slug],
            # args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )

    @property
    def is_updated(self):
        target_datetime = self.publish + timedelta(hours=6)
        if self.updated > target_datetime:
            return True
        return False


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from django.views import View
from django.core.mail import send_mail
from django.db.models import Count
from django.http import Http404
from taggit.models import Tag

# Local imports
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm


class PostListView(View):
    def get(self, request, tag_slug=None):
        list = Post.published.all()
        tags = Tag.objects.all()
        tag = None
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            list = list.filter(tags__in=[tag])
        # Pagination with 3 posts per page
        paginator = Paginator(list, 10)
        page_number = request.GET.get("page", 1)
        try:
            posts = paginator.page(page_number)
        except PageNotAnInteger:
            # If page_number is not an integer deliver the first page
            posts = paginator.page(1)
        except EmptyPage:
            # If page_number is out of range deliver last page of results
            posts = paginator.page(paginator.num_pages)
        return render(
            request, "blog/post_list.html", {"posts": posts, "tag": tag, "tags": tags}
        )


class PostDetailView(View):
    def get(self, request, post):
        post = get_object_or_404(
            Post,
            #  status=Post.Status.PUBLISHED,
            slug=post,
            # publish__year=year,
            # publish__month=month,
            # publish__day=day,
        )
        tags = Tag.objects.all()
        # List of active comments for this post
        comments = post.comments.filter(active=True)
        # Form for users to comment
        form = CommentForm()
        # List of similar posts
        post_tags_ids = post.tags.values_list("id", flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
            id=post.id
        )
        similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
            "-same_tags", "-publish"
        )[:4]
        return render(
            request,
            "blog/blog-detail.html",
            {
                "post": post,
                "comments": comments,
                "tags": tags,
                "form": form,
                "similar_posts": similar_posts,
            },
        )


# def post_detail(request, year, month, day, post):
#     post = get_object_or_404(
#         Post,
#         #  status=Post.Status.PUBLISHED,
#         slug=post,
#         publish__year=year,
#         publish__month=month,
#         publish__day=day,
#     )
#     tags = Tag.objects.all()
#     # List of active comments for this post
#     comments = post.comments.filter(active=True)
#     # Form for users to comment
#     form = CommentForm()
#     # List of similar posts
#     post_tags_ids = post.tags.values_list("id", flat=True)
#     similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
#     similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
#         "-same_tags", "-publish"
#     )[:4]
#     return render(
#         request,
#         "blog/blog-detail.html",
#         {
#             "post": post,
#             "comments": comments,
#             "tags": tags,
#             "form": form,
#             "similar_posts": similar_posts,
#         },
#     )


def share(request, post_id):
    # Retrieve post by id
    # post = get_object_or_404(Post, id=post_id, status=Post.PB)
    post = get_object_or_404(Post, id=post_id)
    sent = False
    if request.method == "POST":
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}'s comments: {cd['comments']}"
            )
            send_mail(subject, message, "dkibui@gmail.com", [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        # status=Post.PUBLISHED
    )
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(
        request,
        "blog/post/comment.html",
        {"post": post, "form": form, "comment": comment},
    )

templates/blog/blog-detail.html
{% extends "_base/_base.html" %}
{% block content %}
<div class="bg-pri-100 px-8 pt-5 pb-8 w-[90%] max-w-[650px] mx-auto rounded-xl text-pri-800 shadow-md">
  <main class="">
    <h1 class="text-xl">{{ post.title }}</h1>
    {% if post.is_updated %}
    <p class="text-xs text-pri-500 font-bold pb-[4px] mb-4 border-b-2 border-pri-300">
      Published {{ post.publish | date:"M d, Y" }}
      | Updated {{ post.updated|timesince }} ago
    </p>
    {% else %}
    <p class="text-xs text-pri-500 font-bold pb-[4px] mb-4 border-b-2 border-pri-300">
      Published {{ post.publish | date:"M d, Y" }}
    </p>
    {% endif %}
    {{ post.body | safe }}
  </main>
  <aside class="right-container">
    <div class="aside-content">
      <div class="tag-filters">
        <h3>Use a tag to filter blogs</h3>
        {% for tag in tags %}
        <a href="{% url 'blog:list_by_tag' tag.slug %}"><span class="tag-baloon">{{ tag.name }}</span></a>
        {% endfor %}
        <a href="{% url 'blog:list' %}"><span class="tag-baloon">remove filter</span></a>
      </div>
      <div class="similar-posts">
        <h3>You might also enjoy the following</h3>
        {% for post in similar_posts %}
        <p>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
        {% empty %}
        We don't have posts with similar content at the moment. Check back later.
        {% endfor %}
      </div>
    </div>
  </aside>
</div>
{% endblock content %}

templates/blog/create-post.html
{% extends "base/base.html" %} {% block content %}
<div class="container">
  <div class="width"><h2>Write your blog post here</h2></div>
  <main class="width">
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{form.as_p}}
      <input type="submit" value="Submit Post" />
    </form>
  </main>
</div>
{% endblock content %}

templates/blog/index.html
{% extends "base/base.html" %}
{% block content %}
<div class="w-11/12 mx-auto border border-blue-500 ">
  {% include 'blog/includes/search.html' %}
  <div class="search-result">
    <div class="width">
      {% if count > 1 and query %}
      <p>Your search <b><i>{{query}}</i></b> found <b>{{count}}</b> blogs</p>
      {% elif count == 1 and query %}
      <p>Your search <b><i>{{query}}</i></b> found <b>{{count}}</b> blog</p>
      {% elif query and count == 0 %}
      <p><b><i>{{query}}</i></b> was not found, try a different term or <b><a href="/"><i>Return</i></a></b> to blogs
      </p>
      {% endif %}
    </div>

    <div class="width">
      {% if count > 1 and tag %}
      <p><b>{{count}}</b> blogs matched <b><i>{{tag}}</i></b></p>
      {% elif count == 1 and tag %}
      <p><b>{{count}}</b> blog matched <b><i>{{tag}}</i></b></p>
      {% endif %}
    </div>
  </div>

  {% for post in page_obj %}
  <article class="width">
    <div data-id="{{post.id}}" class="blog">
      <a href="/{{post.slug}}">
        <h2>{{ post.title }}</h2>
      </a>
      <div class="date-author-tag">
        <div class="date-author">
          <div class="date">Posted {{ post.date_created | timesince }} ago By</div>
          <div class="author">
            <a href="/about/" class="author">{{post.author}}</a>
          </div>
        </div>
        <div class="tags-layout">
          <p>Tags: </p>
          <div class="tags">
            {% for tag in post.tags.all %}
            <a href="{% url " blog-list-tag" tag.slug %}">
              <div class="tag {{ tag }}">{{ tag }}</div>
            </a>
            {% if not forloop.last %} {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="blog-snippet">
        <p>{{ post.content| truncatechars:120 }}</p>
      </div>
    </div>
  </article>
  {% endfor %}
</div>
{% endblock content %}

templates/blog/post_list.html
{% extends "_base/_base.html" %}

{% block content %}
<div class="grid grid-cols-12 w-[90%] mx-auto max-w-[1280px] gap-12">
    <div class="col-span-8">
        <div class="mb-12">{% include "../includes/search.html" %}</div>
        {% for post in posts %}
        <div class="bg-pri-50 px-8 pt-5 pb-8 rounded-xl text-pri-800 shadow-md mb-6">
            <h2 class="text-xl text-zinc-700 font-bold  mb-2">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            <p class="text-xs text-pri-500 font-bold mb-0">Published {{ post.publish | date:"M d, Y" }}</p>
            <div class="">{{ post.body | safe | truncatechars_html:240 }}</div>
        </div>
        {% endfor %}
    </div>
    <aside class="col-span-4 text-pri-800 mt-[97px]">
        <div class="">
            <h3 class="mt-0">All blogs - ({{ tags.count }})</h3>
            {% for tag in tags %}
            <div
                class="bg-pri-50 px-4 py-2 rounded-full mb-2 mr-1 inline-block cursor-pointer outline hover:outline-[3px] outline-pri-300 ">
                <a href="{% url 'blog:list_by_tag' tag.slug %}" class="block">
                    <span class="">{{ tag.name.title }}</span></a>
            </div>
            {% endfor %}
            <div
                class="bg-pri-50 px-4 py-2 rounded-full mb-2 mr-1 inline-block cursor-pointer outline hover:outline-4 outline-pri-300 ">
                <a href="{% url 'blog:list' %}">
                    <span class="">Remove filter</span>
                </a>
            </div>
        </div>
    </aside>
</div>
{% endblock content %}

templates/blog/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static "css/style.css" %} />
    <title>Document</title>
</head>
<body>
    <div class="left-container">
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis temporibus, earum nostrum blanditiis repudiandae placeat totam dolor quod deserunt molestias porro, ad, recusandae cum reprehenderit eos ipsa nulla culpa laudantium.
        </p>
        <p>
            Dignissimos modi ad nostrum nesciunt illum perspiciatis? Dolorum atque, repudiandae nihil minima consequatur illum dolores reiciendis perferendis placeat? Sapiente provident nesciunt eos debitis excepturi dolorum aspernatur ut, earum quam possimus.
        </p>
    </div>
    <div class="center-container">
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis temporibus, earum nostrum blanditiis repudiandae placeat totam dolor quod deserunt molestias porro, ad, recusandae cum reprehenderit eos ipsa nulla culpa laudantium.
        </p>
        <p>
            Dignissimos modi ad nostrum nesciunt illum perspiciatis? Dolorum atque, repudiandae nihil minima consequatur illum dolores reiciendis perferendis placeat? Sapiente provident nesciunt eos debitis excepturi dolorum aspernatur ut, earum quam possimus.
        </p>
    </div>
    <div class="right-container">
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis temporibus, earum nostrum blanditiis repudiandae placeat totam dolor quod deserunt molestias porro, ad, recusandae cum reprehenderit eos ipsa nulla culpa laudantium.
        </p>
        <p>
            Dignissimos modi ad nostrum nesciunt illum perspiciatis? Dolorum atque, repudiandae nihil minima consequatur illum dolores reiciendis perferendis placeat? Sapiente provident nesciunt eos debitis excepturi dolorum aspernatur ut, earum quam possimus.
        </p>
    </div>
</body>
</html>